/*
==============================================================================================
Magnitude Analysis
==============================================================================================

Script Purpose: 
    Compares the measure values across different categories
    This script performs magnitude analysis across key dimensions such as 
    geography, demographics, products, and revenue.
    It helps quantify customer counts, product distribution, and revenue contributions.

Usage:
    - Identify which countries and demographics contribute the most customers.
    - Analyze product categories by count, cost, and revenue.
    - Understand customer-level revenue contribution.
    - Explore sales distribution by geography.
==============================================================================================
*/


-- ==============================================================================================
-- Step 1: Find total customers by country
-- ==============================================================================================
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- ==============================================================================================
-- Step 2: Find total customers by gender
-- ==============================================================================================
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- ==============================================================================================
-- Step 3: Find total products by category
-- ==============================================================================================
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- ==============================================================================================
-- Step 4: Find average product cost per category
-- ==============================================================================================
SELECT 
category,
AVG(product_cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- ==============================================================================================
-- Step 5: Find total revenue generated per category
-- ==============================================================================================
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- ==============================================================================================
-- Step 6: Find total revenue generated by each customer
-- ==============================================================================================
SELECT 
c.customer_id,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_id,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- ==============================================================================================
-- Step 7: Find the distribution of sold items across countries
-- ==============================================================================================
SELECT
country,
SUM(quantity) AS sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY country
ORDER BY sold_items DESC


